version: '3.8'
services:
  backend:
    build: ./backend
    env_file: .env.example
    ports:
      - '5000:5000'
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
